project:
  type: website
  output-dir: docs

website:
  title: "TC2again"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 2Answers.qmd
        text: Answers

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pptx: default
  docx: default
  pdf: default



